apiVersion: v2
name: ledger
description: The core ledger service chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.3.0"

dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.8.0
    condition: cert-manager.install
  - name: reloader
    repository: https://stakater.github.io/stakater-charts
    version: 0.0.114
    condition: reloader.enabled
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: 15.10.1
    condition: prometheus.enabled    
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 6.29.6
    condition: grafana.enabled