{{- if and .Values.tls.enabled (not .Values.tls.ca.issuer) }}
apiVersion: cert-manager.io/v1
kind: {{if $.Values.tls.ca.cluster -}}ClusterIssuer{{- else -}}Issuer{{- end }} 
metadata:
  name: {{ include "chart.fullname" . }}-issuer
  labels:
    app.kubernetes.io/component: tls
    {{- include "chart.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "chart.fullname" . }}-ca-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "chart.fullname" . }}-ca
  {{- with .Values.tls.ca.cluster }}
  namespace: cert-manager
  {{- end}}
  labels:
    app.kubernetes.io/component: tls
    {{- include "chart.labels" . | nindent 4 }}
spec:
  isCA: true
  duration: {{ .Values.tls.ca.duration }}
  commonName: {{ default .Values.tls.ca.common (printf "%s-%s" (include "chart.fullname" .) "ca") }}
  secretName: {{ include "chart.fullname" . }}-ca-tls
  {{- with .Values.tls.ca.privateKey }}
  privateKey:
    {{- toYaml . | nindent 4 }}
  {{- end }}  
  {{- with .Values.tls.ca.subject }}
  subject: 
    {{- toYaml . | nindent 4 }}
  {{- end }}  
  {{- with .Values.tls.ca.usages }}
  usages:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tls.ca.dnsNames }}
  dnsNames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tls.ca.ipAddresses }}
  ipAddresses:
    {{- toYaml . | nindent 4 }}
  {{- end }} 
  {{- with .Values.tls.ca.issuer }}
  issuerRef:
    {{- toYaml . | nindent 4 }}
  {{- else}}  
  issuerRef:
    group: cert-manager.io
    kind: {{ if $.Values.tls.ca.cluster -}}ClusterIssuer{{- else -}}Issuer{{- end }}
    name: {{ include "chart.fullname" . }}-issuer-selfsigned
  {{- end }}  
{{- if not .Values.tls.ca.issuer }}    
---
apiVersion: cert-manager.io/v1
kind: {{ if $.Values.tls.ca.cluster -}}ClusterIssuer{{- else -}}Issuer{{- end }}
metadata:
  name: {{ include "chart.fullname" . }}-issuer-selfsigned
  labels:
    app.kubernetes.io/component: tls
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
{{- end }}