{{- if not .Values.replica.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- if .Values.podAnnotations }}
  annotations:
    {{ toYaml .Values.podAnnotations | indent 6 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: {{ $.Values.ledger.logLevel }}
            - name: BATCH_SIZE
              value: {{ $.Values.ledger.batchSize | quote }}
            - name: CLIENT_OPTIONS_ADDRESS
              value: {{ $.Values.immudb.address }}
            - name: CLIENT_OPTIONS_PORT
              value: {{ $.Values.immudb.port | quote }}
            - name: CLIENT_OPTIONS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "chart.fullname" . }}
                  key: IMMUDB_USER
            - name: CLIENT_OPTIONS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "chart.fullname" . }}
                  key: IMMUDB_PASSWORD
            - name: CLIENT_OPTIONS_MTLS
              value: {{ $.Values.immudb.mtls.enabled | quote }}
            - name: CLIENT_OPTIONS_DATABASE
              value: {{ $.Values.immudb.dbName }}
            - name: CLIENT_OPTIONS_MTLS_OPTIONS_CERTIFICATE
              value: {{ $.Values.immudb.mtls.certFile }}
            - name: CLIENT_OPTIONS_MTLS_OPTIONS_CLIENT_CAS
              value: {{ $.Values.immudb.mtls.caFile }}
            - name: CLIENT_OPTIONS_MTLS_OPTIONS_PKEY
              value: {{ $.Values.immudb.mtls.keyFile }}
            - name: CLIENT_OPTIONS_MTLS_OPTIONS_SERVERNAME
              value: {{ $.Values.immudb.mtls.serverName }}

            - name: SERVICE_ACCESS_LOGGER
              value: {{ $.Values.ledger.accessLogger | quote }}
            - name: SERVICE_METRICS
            {{- if $.Values.ledger.metrics.enabled }}
              value: {{ $.Values.ledger.metrics.port | quote }}
            {{- else }}
              value: "0"
            {{- end}}  
            - name: SERVICE_PORT
            {{- if $.Values.ledger.metrics.enabled }}
              value: "8443"
            {{- else }}
              value: "8080"
            {{- end }}  
            - name: SERVICE_PRODUCTION
              value: {{ $.Values.ledger.production | quote }}
            - name: SERVICE_SERVERNAME
              value: {{ $.Values.ledger.serverName | quote }}
            {{- if $.Values.ledger.mtls.enabled }}
            - name: SERVICE_MTLS_CERTIFICATE
              value: {{ $.Values.ledger.mtls.certFile }}
            - name: SERVICE_MTLS_CLIENT_CAS
              value: {{ $.Values.ledger.mtls.caFile }}
            - name: SERVICE_MTLS_PKEY
              value: {{ $.Values.ledger.mtls.keyFile }}
            {{- end }}
          ports:
            - name: web
            {{- if $.Values.ledger.mtls.enabled }}
              containerPort: 8443
            {{- else }}
              containerPort: 8080
            {{- end }}  
              protocol: TCP
            {{- if $.Values.ledger.metrics.enabled }}
            - name: metrics
              containerPort: {{ $.Values.ledger.metrics.port }}
              protocol: TCP
            {{- end }}  
          volumeMounts:
            - name: immudb-ledger-client
              mountPath: /certs/immudb
            - name: ledger-server
              mountPath: /certs/server
          {{- if $.Values.ledger.metrics.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: metrics
          readinessProbe:
            httpGet:
              path: /health
              port: metrics
          {{- end }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if (or $.Values.ledger.mtls.enabled $.Values.immudb.mtls.enabled) }}
      volumes:
        {{- if $.Values.ledger.mtls.enabled }}
        - name: immudb-ledger-client
          secret:
            secretName: {{ include "chart.fullname" . }}-immudb-client-tls
            defaultMode: 420
        {{- end }}    
        {{- if $.Values.immudb.mtls.enabled }}
        - name: ledger-server
          secret:
            {{- if $.Values.certs.immudb.generated }}
            secretName: {{ include "chart.fullname" . }}-server-tls
            {{- else }}
            secretName: {{ $.Values.certs.immudb.seceret }}
            {{- end }}
            defaultMode: 420
        {{- end }}    
      {{- end }}      
{{- end }}