---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
type: Opaque
data:
  IMMUDB_PASSWORD: {{ $.Values.immudb.user.password | b64enc }}
  IMMUDB_USER: {{ $.Values.immudb.user.name | b64enc }}
{{- if $.Values.certs.client.keystore.pkcs12.enabled }}  
  PKCS12_PASSWORD: {{ $.Values.certs.client.keystore.pkcs12.password | b64enc }}
{{- end }}
---
{{- $root := . -}}
{{- $gob := .Files.Glob "gcr.json" }}
{{- if $gob }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-gcr
type: kubernetes.io/dockerconfigjson  
data:
{{- range $path, $bytes := .Files.Glob "gcr.json" }}
  ".dockerconfigjson": {{ $root.Files.Get $path | b64enc | quote }}
{{- end }}
{{- end }}