package main

import (
	"io/fs"
	"io/ioutil"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ec-systems/core.ledger.tool/cmd"
	"github.com/ec-systems/core.ledger.tool/pkg/config"
	"github.com/ec-systems/core.ledger.tool/pkg/logger"
)

var (
	appEnvFile  = "examples/env.sample.sh"
	exampleConf = "conf.sample"

	DoNotEdit = "Code generated by example generator. DO NOT EDIT.\n"
)

func main() {
	path, err := os.Getwd()
	if err != nil {
		logger.Fatalf("Getwd: %v", err)
	}

	root := cmd.GetRootCmd(&cmd.Version{})

	env, err := GroupBindings(root.EnvBindings())
	if err != nil {
		logger.Fatalf("GroupedBindings: %v", err)
	}

	lines := []string{"# " + DoNotEdit}

	for _, g := range env {
		items := []string{}

		for _, v := range g {
			items = append(items, v)
		}

		sort.Strings(items)

		for _, v := range items {
			lines = append(lines, v+"=")
		}

		lines = append(lines, "")
	}

	appEnvFilePath := filepath.Join(path, appEnvFile)
	logger.Infof("Write app env example file: %v", appEnvFilePath)
	err = ioutil.WriteFile(appEnvFilePath, []byte(strings.Join(lines, "\n")), fs.ModePerm)
	if err != nil {
		logger.Fatalf("Error write %v: %v", appEnvFilePath, err)
	}

	cfg := config.Configuration()

	exampleConfPath := filepath.Join(path, "examples", exampleConf)

	for _, f := range []string{"json", "yaml", "toml"} {
		filename := exampleConfPath + "." + f
		data, err := Marshal(cfg, filename)
		if err != nil {
			logger.Fatalf("Error marshal config %v: %v", filename, err)
		}

		if f != "json" {
			data = []byte("# " + DoNotEdit + string(data))
		}

		logger.Infof("Write example conf file: %v", filename)
		err = ioutil.WriteFile(filename, data, fs.ModePerm)
		if err != nil {
			logger.Fatalf("Error write %v: %v", filename, err)
		}
	}
}
