//Code generated by assets generator. DO NOT EDIT.
package types

const (
	XRP Asset = "XRP"
	Cardano Asset = "ADA"
	Bitcoin Asset = "BTC"
	Ethereum Asset = "ETH"
	Tether Asset = "USDT"
	USDCoin Asset = "USDC"
	BNB Asset = "BNB"
)

var DefaultAssetNames = Assets{
	"Tether": "USDT",
	"USDCoin": "USDC",
	"BNB": "BNB",
	"XRP": "XRP",
	"Cardano": "ADA",
	"Bitcoin": "BTC",
	"Ethereum": "ETH",
}

var DefaultAssetMap = Assets{
	"XRP": XRP,
	"ADA": Cardano,
	"BTC": Bitcoin,
	"ETH": Ethereum,
	"USDT": Tether,
	"USDC": USDCoin,
	"BNB": BNB,
}
