//Code generated by statuses generator. DO NOT EDIT.
package types

const (
	Unknown Status = -1
	Created Status = 0
	CancellationFinished Status = 998
	Canceled Status = 999
	Finished Status = 1000
)

var DefaultStatusMap = Statuses{
	"Unknown": Unknown,
	"Created": Created,
	"CancellationFinished": CancellationFinished,
	"Canceled": Canceled,
	"Finished": Finished,
}
