//Code generated by statuses generator. DO NOT EDIT.
package types

const (
	Settled Status = 100
	PayedOut Status = 101
	Finished Status = 1000
	Unknown Status = -1
	Created Status = 0
)

var DefaultStatusMap = Statuses{
	"Unknown": Unknown,
	"Created": Created,
	"Settled": Settled,
	"PayedOut": PayedOut,
	"Finished": Finished,
}
