basePath: /
definitions:
  ledger.Transaction:
    properties:
      Item:
        type: string
      Order:
        type: string
      account:
        type: string
      amount:
        type: number
      asset:
        type: string
      created:
        type: string
      holder:
        type: string
      id:
        type: string
      modified:
        type: string
      reference:
        type: string
      status:
        type: integer
      user:
        type: string
    type: object
  service.Account:
    properties:
      account:
        type: string
      asset:
        type: string
    type: object
  service.Asset:
    properties:
      name:
        type: string
      symbol:
        type: string
    type: object
  service.Holder:
    properties:
      accounts:
        items:
          $ref: '#/definitions/service.Account'
        type: array
      name:
        type: string
    type: object
  service.Status:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact:
    email: support@easycrypto.ai
    name: Easy Crypto Core Team
    url: http://easycrypto.ai
  description: This is the web service of the core asset ledger.
  title: Core Ledger
paths:
  /accounts/:
    get:
      description: List all holders in the ledger
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.Holder'
            type: array
        "404":
          description: ""
        "500":
          description: ""
      summary: List Holders
      tags:
      - Accounts
  /accounts/{holder}:
    get:
      description: List accounts and balances of a holder
      parameters:
      - description: Account Holder
        in: path
        name: holder
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ledger.Transaction'
            type: array
        "404":
          description: ""
        "500":
          description: ""
      summary: List User Accounts
      tags:
      - Accounts
  /accounts/{holder}/{asset}:
    get:
      description: List accounts and balances of a asset of a holder
      parameters:
      - description: Account Holder
        in: path
        name: holder
        required: true
        type: string
      - description: Asset Symbol
        in: path
        name: asset
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ledger.Transaction'
            type: array
        "404":
          description: ""
        "500":
          description: ""
      summary: List Asset Accounts
      tags:
      - Accounts
  /accounts/{holder}/{asset}/{account}:
    get:
      description: List all the transactions of an account
      parameters:
      - description: Account Holder
        in: path
        name: holder
        required: true
        type: string
      - description: Asset Symbol
        in: path
        name: asset
        required: true
        type: string
      - description: Account
        in: path
        name: account
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ledger.Transaction'
        "404":
          description: ""
        "500":
          description: ""
      summary: List Transactions
      tags:
      - Accounts
  /accounts/{holder}/{asset}/{account}/{id}:
    delete:
      description: Remove or add assets from ledger by reverting a transaction
      parameters:
      - description: Account Holder
        in: path
        name: holder
        required: true
        type: string
      - description: Asset Symbol
        in: path
        name: asset
        required: true
        type: string
      - description: Account
        in: path
        name: account
        required: true
        type: string
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ledger.Transaction'
        "400":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      summary: Revert a Transaction
      tags:
      - Accounts
    get:
      description: Show the history of a transaction
      parameters:
      - description: Account Holder
        in: path
        name: holder
        required: true
        type: string
      - description: Asset Symbol
        in: path
        name: asset
        required: true
        type: string
      - description: Account
        in: path
        name: account
        required: true
        type: string
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ledger.Transaction'
            type: array
        "404":
          description: ""
        "500":
          description: ""
      summary: Show History
      tags:
      - Accounts
    patch:
      description: Change the status of a transaction
      parameters:
      - description: Account Holder
        in: path
        name: holder
        required: true
        type: string
      - description: Asset Symbol
        in: path
        name: asset
        required: true
        type: string
      - description: Account
        in: path
        name: account
        required: true
        type: string
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ledger.Transaction'
        "404":
          description: ""
        "500":
          description: ""
      summary: Change the Transaction Status
      tags:
      - Accounts
  /accounts/{holder}/{asset}/{amount}:
    delete:
      description: Remove assets to the ledger
      parameters:
      - description: Account Holder
        in: path
        name: holder
        required: true
        type: string
      - description: Asset Symbol
        in: path
        name: asset
        required: true
        type: string
      - description: Amount
        in: path
        name: amount
        required: true
        type: string
      - description: Order ID
        in: query
        name: order
        type: string
      - description: Order Item ID
        in: query
        name: item
        type: string
      - description: Reference
        in: query
        name: ref
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ledger.Transaction'
        "400":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      summary: Remove Assets
      tags:
      - Accounts
    put:
      description: Add assets to the ledger
      parameters:
      - description: Account Holder
        in: path
        name: holder
        required: true
        type: string
      - description: Asset Symbol
        in: path
        name: asset
        required: true
        type: string
      - description: Amount
        in: path
        name: amount
        required: true
        type: string
      - description: Order ID
        in: query
        name: order
        type: string
      - description: Order Item ID
        in: query
        name: item
        type: string
      - description: Reference
        in: query
        name: ref
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ledger.Transaction'
        "400":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      summary: Add Assets
      tags:
      - Accounts
  /health:
    get:
      description: Show health status
      produces:
      - plain/text
      responses:
        "200":
          description: ""
        "500":
          description: ""
      summary: Health
      tags:
      - Health
  /info/assets:
    get:
      description: List of the assets supported by the ledger
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.Asset'
            type: array
      summary: Supported Assets
      tags:
      - Info
  /info/statuses:
    get:
      description: List of the statuses supported by the ledger
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/service.Status'
              type: array
            type: array
      summary: Supported Statuses
      tags:
      - Info
swagger: "2.0"
